config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => { registrations: 'registrations' }

  root 'items#index'

  resources :users, :only => [:show, :index, :edit]

  resources :items, :only => [:index, :new, :create, :update]

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user

	validates(:user, :presence => true)

	has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :items, dependent: :destroy

         validates(:handle, :presence => true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :load_items, :only => [:index, :create]
  before_action :load_new_item, :only => [:index, :new]

  def index
  end

  def new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to '/items'
    else
      render :index
    end
  end

  def show
    
  end


  private

    def item_params
      params["item"].permit(:body, :photo).merge(:user => current_user)
    end

    def load_new_item
      @item = Item.new
    end

    def load_items
      @items = Item.all
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  protected

  # my custom fields are :name, :heard_how
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:handle, :avatar, :name,
        :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:handle, :avatar, :current_password,
        :email, :password, :password_confirmation, :name)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!
	
	def show
   		@user = User.find(params[:id])
    	@items = @user.items
 	end

 	def index
 	   @users = User.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_errors.html.erb
<% if item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/items/_form.html.erb
<%= form_for(item, {:url => "/items", :html => {:multipart => true}}) do |f| %>
  <%= f.label :body %>:
  <%= f.text_field :body %>

  <br/>
 	<%= f.label :photo %>:
	<%= f.file_field :photo %>
<br/>
  <%= f.submit %>
<% end %> 

app/views/items/index.html.erb
<h4>Items</h4>

<%= render :partial => 'errors', :locals => {:item => @item} %>

<br/><br/>
<%= render :partial => 'form', :locals => {:item => @item} %>
<br/>

<ul>
<% @items.each do |item| %>
  <li><%= link_to(item.user.handle, "/users/#{item.user.id}") %>: <%= item.body %></li>
		<%= image_tag item.photo.url(:medium) %>

<% end %>
</ol>

app/views/items/new.html.erb
<h4>New Item</h4>

<%= render :partial => 'form', :locals => {:item => @item} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterst</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
    Signed in as <%=current_user.handle%> | 
    <%=link_to 'Sign Out', destroy_user_session_path, :method => :delete %> | <%=link_to 'Edit Profile', edit_user_registration_path %>
  <% else %>
    <%= link_to 'Sign In', user_session_path %>
  <% end %>

  <% if (current_page?(controller: 'users', action: 'show', id: current_user.id)) %>
    <%=link_to 'Home Page', items_path %>
    <% end %>

  <%= yield %>


    
</div>

</body>
</html>

app/views/users/_item.html.erb
<tr>
  <td>
    <div class="item_body">
      <%= item.body %>
    </div>
    <%= image_tag item.photo.url(:medium) %> 
    <div class="item_timestamp">
      <%= time_ago_in_words(item.created_at) %> ago
    </div>
	<br/>
	<br/>
  </td>
</tr>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.handle, "/users/#{user.id}" %>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="pinterest_profile">
  <table>
    <tr>
    </tr>
    <tr>
     <td>
        <div class="pinterest_handle"> <b> <%= @user.handle %> : </b></div>
      </td>
    </tr>
  </table>
</div>


<ol>
<table class="items_list">
<% @items.each do |item| %>
 <%= render partial: "item", locals: {item: item} %> 
<% end %>
</ol>

</table>